# -*- coding: utf-8 -*-
"""성능평가_v2.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1KsBrNR7ZygBPBWKzn1LGHIO1uwkXQvHQ

# 성능 평가 지표 (수정판)

## 사용 지표
1. **방법별 분류 현황** - keyword_ai_verified / ai_corrected / ai_direct / keyword_only 분포
2. **카테고리 분포** - 6개 카테고리 건수 및 비율
3. **키워드-AI 일치도** - 키워드가 제안한 카테고리와 AI 최종 판단의 일치율
4. **혼동 패턴 분석** - AI가 키워드를 어느 방향으로 수정하는지
5. **신뢰도 분포** - very_high / high / medium / low 비율

## 수정 이유
- ROUGE: ai_reason이 없는 keyword_ai_verified(57.5%) 케이스 제외됨 → 불공정
- Confidence를 정확도로 사용: "확신"≠"정확" → 의미없는 지표
- keyword_suggested 없는 케이스 누락 → 수정
"""

import json
import pandas as pd
from collections import Counter

# 파일 경로 설정
HYBRID_FILE = "hybrid_results_20260211_170044.json"
CLASSIFIED_FILE = "data_classified_20260211_170044.json"

# 데이터 로드
with open(HYBRID_FILE, 'r', encoding='utf-8') as f:
    hybrid_data = json.load(f)

results = hybrid_data['results']
meta = hybrid_data['metadata']
total = meta['total']

print("=" * 65)
print("📊 1. 분류 방법별 현황")
print("=" * 65)

method_labels = {
    "keyword_ai_verified": "✅ 키워드 + AI 일치",
    "ai_corrected":        "⚠️  AI가 키워드 수정",
    "ai_direct":           "🤖 AI 직접 분류",
    "keyword_only":        "❗ AI 실패 (키워드만 사용)"
}

method_dist = Counter(r.get('method') for r in results)
for method, label in method_labels.items():
    count = method_dist.get(method, 0)
    print(f"  {label:<25}: {count:>5}건 ({count/total*100:>5.1f}%)")

print(f"\n  총계: {total}건")
print(f"  비용: ₩{meta.get('cost', 0):,.0f}")
print(f"  시간: {meta.get('time_seconds', 0)/3600:.1f}시간")

print("\n" + "=" * 65)
print("📊 2. 카테고리 분포")
print("=" * 65)

VALID_CATEGORIES = ["윤리/부패/비위","인사/채용/복무","정보보안/IT","시설/안전/환경","재무/회계/계약","사업/운영/성과"]
cat_dist = Counter(r.get('category') for r in results)

for cat in VALID_CATEGORIES:
    count = cat_dist.get(cat, 0)
    bar = "█" * (count * 30 // total)
    print(f"  {cat:<20}: {count:>5}건 ({count/total*100:>5.1f}%) {bar}")

invalid = {k: v for k, v in cat_dist.items() if k not in VALID_CATEGORIES}
if invalid:
    print(f"\n⚠️  이상값: {invalid}")
else:
    print("\n✅ 카테고리 이상값 없음 (6개 완벽)")

print("\n" + "=" * 65)
print("📊 3. 신뢰도 분포")
print("=" * 65)

conf_dist = Counter(r.get('confidence') for r in results)
conf_order = ["very_high", "high", "medium", "low", "very_low"]
for conf in conf_order:
    count = conf_dist.get(conf, 0)
    if count > 0:
        print(f"  {conf:<12}: {count:>5}건 ({count/total*100:>5.1f}%)")

"""## 키워드-AI 일치도 분석

`keyword_ai_verified`: 키워드와 AI가 같은 카테고리 → 해당 키워드의 **정확도 증거**  
`ai_corrected`: AI가 키워드와 다른 카테고리로 수정 → **키워드의 한계** 드러남

### 수정 포인트
- 기존: `keyword_suggested` 필드만 봄 → `keyword_ai_verified` 2,853건 누락
- 수정: `keyword` 필드로 통합 분석 (모든 키워드 매칭 케이스 포함)

"""

import json
import pandas as pd
from collections import defaultdict

with open("hybrid_results_20260211_170044.json", 'r', encoding='utf-8') as f:
    hybrid_data = json.load(f)

results = hybrid_data['results']

# 키워드가 사용된 케이스 전체 분석
# keyword_ai_verified: keyword == AI → is_match = 1
# ai_corrected: keyword != AI → is_match = 0
# keyword_only: AI 실패 → is_match = None (제외)

analysis = []
for r in results:
    method = r.get('method', '')
    keyword = r.get('keyword')
    final_cat = r.get('category')

    if not keyword:
        continue  # ai_direct는 키워드 없음

    if method == 'keyword_ai_verified':
        # 키워드 카테고리 = AI 카테고리 (일치)
        keyword_cat = final_cat  # 동일하므로
        analysis.append({'keyword': keyword, 'keyword_cat': keyword_cat,
                         'ai_cat': final_cat, 'is_match': 1, 'method': method})

    elif method == 'ai_corrected':
        # keyword_suggested = 키워드 원래 카테고리
        keyword_cat = r.get('keyword_suggested', '')
        if keyword_cat:
            analysis.append({'keyword': keyword, 'keyword_cat': keyword_cat,
                             'ai_cat': final_cat, 'is_match': 0, 'method': method})

df = pd.DataFrame(analysis)
total_kw = len(df)

print("=" * 65)
print("📊 4. 키워드-AI 일치도 분석")
print("=" * 65)
print(f"\n키워드 매칭 케이스 전체: {total_kw}건")
print(f"  일치 (keyword_ai_verified): {df['is_match'].sum():.0f}건 ({df['is_match'].mean()*100:.1f}%)")
print(f"  수정 (ai_corrected):        {(1-df['is_match']).sum():.0f}건 ({(1-df['is_match'].mean())*100:.1f}%)")

print("\n" + "=" * 65)
print("📊 5. 카테고리별 키워드 신뢰도")
print("=" * 65)
print("(키워드로 분류했을 때 AI가 동의한 비율)")
print()

perf = df.groupby('keyword_cat')['is_match'].agg(['count','sum','mean'])
perf.columns = ['키워드 사용', 'AI 동의', '일치율']
perf['일치율(%)'] = (perf['일치율'] * 100).round(1)
perf = perf.sort_values('일치율(%)', ascending=False)

for cat, row in perf.iterrows():
    bar = "█" * int(row['일치율(%)']/5)
    print(f"  {cat:<20}: {row['일치율(%)']:>5.1f}%  ({row['AI 동의']:.0f}/{row['키워드 사용']:.0f}건) {bar}")

print("\n" + "=" * 65)
print("📊 6. AI 수정 패턴 (혼동 행렬)")
print("=" * 65)
print("(키워드→카테고리 A로 분류했는데 AI가 B로 바꾼 패턴)")
print()

overrides = df[df['is_match'] == 0]
confusion = overrides.groupby(['keyword_cat', 'ai_cat']).size().reset_index(name='수정건수')
confusion = confusion.sort_values('수정건수', ascending=False)

for _, row in confusion.head(10).iterrows():
    print(f"  [{row['keyword_cat']}] → [{row['ai_cat']}]: {row['수정건수']}건")


"""
LLM-as-a-Judge: 문맥 정합성 측정

AI 판사가 `ai_reason`이 해당 카테고리 정의와 논리적으로 일치하는지 0~100점으로 채점.  
**주의**: ai_reason이 없는 `keyword_ai_verified` 케이스는 제외됨 (ai_corrected, ai_direct만 평가)
"""


import json
import time
import os
import re
import random  # ← 추가!
from langchain_community.chat_models import ChatClovaX
from langchain_core.messages import HumanMessage
from dotenv import load_dotenv

# 1. .env 파일 로드
load_dotenv()
CLOVA_API_KEY = os.getenv("CLOVASTUDIO_API_KEY")

print("\n" + "=" * 65)
print("📊 7. LLM-as-a-Judge: 문맥 정합성 측정")
print("=" * 65)

# 카테고리 정의
CATEGORY_DEFINITIONS = {
    "윤리/부패/비위": "금품수수, 뇌물, 횡령, 비리, 청탁, 갑질 등 공직기강 및 부패 관련 사안",
    "인사/채용/복무": "채용 부정, 인사 불공정, 근태 관리, 성희롱, 출장 및 복무 규정 위반",
    "정보보안/IT": "개인정보 유출, 보안 위반, 시스템 장애 및 IT 자산 관리 부적정",
    "시설/안전/환경": "안전사고, 시설 결함, 부실 시공, 재난 예방 및 환경오염 관련 사안",
    "재무/회계/계약": "예산/회계 오류, 계약 위반, 정산 누락, 비용 및 금액 산정 부적정",
    "사업/운영/성과": "업무 지연, 지침 미준수, 관리 소홀, 사업 평가 및 성과 관리 부적정"
}


def evaluate_semantic_alignment(file_path, sample_size=50):
    # 파일 존재 여부 확인
    if not os.path.exists(file_path):
        print(f"❌ 오류: '{file_path}' 파일을 찾을 수 없습니다. 경로를 확인해주세요.")
        return

    with open(file_path, 'r', encoding='utf-8') as f:
        data = json.load(f)

    # JSON 구조 대응
    items = data.get('results', data)

    # ai_reason이 있는 케이스만 필터링
    items_with_reason = [r for r in items if r.get('ai_reason', '').strip()]
    
    # [수정] 랜덤 샘플링 (재현성을 위해 seed 고정)
    random.seed(42)
    if len(items_with_reason) > sample_size:
        sample = random.sample(items_with_reason, sample_size)
        print(f"📌 {len(items_with_reason)}건 중 랜덤 {sample_size}건 샘플링")
    else:
        sample = items_with_reason
        print(f"💡 ai_reason이 있는 데이터가 {len(items_with_reason)}건이므로 전체를 평가합니다.")
        
    if not CLOVA_API_KEY:
        print("❌ 오류: .env 파일에서 CLOVASTUDIO_API_KEY를 찾을 수 없습니다.")
        return

    # ChatClovaX 설정
    chat = ChatClovaX(
        model="HCX-003",
        ncp_clovastudio_api_key=CLOVA_API_KEY,
        temperature=0.1
    )

    scores = []
    print(f"⚖️  AI 판사 평가 중 (샘플 {len(sample)}건)...\n")

    for i, item in enumerate(sample, 1):
        cat = item.get('category', '')
        reason = item.get('ai_reason', '')
        definition = CATEGORY_DEFINITIONS.get(cat, "정의 없음")

        prompt = f"""감사 결과 분류의 타당성을 검토하세요.
[카테고리명]: {cat}
[카테고리 정의]: {definition}
[AI 분류 근거]: {reason}

0~100점으로 채점하고 JSON으로 답하세요.
형식: {{"score": 점수, "reason": "이유"}}"""

        try:
            resp = chat.invoke([HumanMessage(content=prompt)])
            # JSON 추출
            match = re.search(r'\{.*\}', resp.content, re.DOTALL)
            if match:
                result = json.loads(match.group())
                score = result.get('score', 0)
                scores.append(score)
                print(f"  [{i:02d}/{len(sample)}] idx {item.get('idx')}: {score}점 - {result.get('reason','')[:40]}")
            
            time.sleep(1.2)  # API 호출 제한 방지
            
        except Exception as e:
            print(f"  [{i:02d}/{len(sample)}] idx {item.get('idx')} 오류: {e}")
            continue

    # 최종 결과 통계 출력
    if scores:
        print(f"\n  평가 건수: {len(scores)}건 (ai_reason 있는 케이스)")
        print(f"  평균 정합성 점수: {sum(scores)/len(scores):.1f}점 / 100점")
        print(f"  80점 이상: {sum(1 for s in scores if s >= 80)}건 ({sum(1 for s in scores if s >= 80)/len(scores)*100:.1f}%)")
        print(f"  60점 미만: {sum(1 for s in scores if s < 60)}건 ({sum(1 for s in scores if s < 60)/len(scores)*100:.1f}%)")
        print("=" * 65)
    else:
        print("\n❌ 평가 가능한 데이터가 없습니다.")

# 실행
if __name__ == "__main__":
    evaluate_semantic_alignment("hybrid_results_20260211_170044.json", sample_size=50)